version: '3'

# Перечисление подключаемых сервисов (технологий)
services:
  # Нарицательное очередного подключаемого сервиса
  nginx:
    # Тот образ который будет искаться на dockerHub, если его нет локально
    image: nginx:latest
    # Порт конкретно для этого контейнера
    ports:
      - "8876:80"