version: '3'

# Перечисление подключаемых сервисов (технологий)
services:
  # Нарицательное очередного подключаемого сервиса
  nginx:
    # Тот образ который будет искаться на dockerHub, если его нет локально
    image: nginx:latest
    # транслирование локальных файлов в контейнер
    volumes:
      - ./:/var/www/
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      # Порт конкретно для этого контейнера
    ports:
      - "8876:80"
    # Свое название сервиса (вместо "nginx-nginx-1")
    container_name: app_nginx